import type { Metadata } from 'next'
import { Inter, Prompt, Capriola } from 'next/font/google'
import './globals.css'
import AntdRegistry from '@/components/helpers/AntdRegistry'

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
})

const capriola = Capriola({
    subsets: ['latin'],
    weight: '400',
    variable: '--font-capriola',
})

const prompt = Prompt({
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-prompt',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={`${inter.variable} ${prompt.variable} ${capriola.variable}`}>
                <AntdRegistry>{children}</AntdRegistry>
            </body>
        </html>
    )
}
